### ISSUE TITLE
? modifier on G or M Codes terminates active print and doesn't provide expected help text

### ISSUE THREAD

**Issue by cwhinton** [intelligent-agent/redeem#112]
2.1.x RC7

Attempted M106? to display the expected options and use while printing.  This kills the print.  Recover was to restart Redeem. 

Text from syslog:
```
Exception in thread Pipe:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Redeem-0+untagged.1.pip10.g7351c6e.dirty-py2.7-linux-armv7l.egg/redeem/Pipe.py", line 89, in get_message
    self.printer.processor.enqueue(g)
  File "/usr/local/lib/python2.7/dist-packages/Redeem-0+untagged.1.pip10.g7351c6e.dirty-py2.7-linux-armv7l.egg/redeem/GCodeProcessor.py", line 129, in enqueue
    self.resolve(gcode)
  File "/usr/local/lib/python2.7/dist-packages/Redeem-0+untagged.1.pip10.g7351c6e.dirty-py2.7-linux-armv7l.egg/redeem/GCodeProcessor.py", line 94, in resolve
    gcode.command = self.gcodes[gcode.code()]
KeyError: 'M106?'
2018-05-14 17:12:51,357 - octoprint.util.comm - INFO - Communication timeout while printing, trying to trigger response from printer.
```

**Comment by Wackerbarth** [comment]
This was already fixed in `2.2`
